name: 96zero.com
favicon: null
layout_spectrum: 0.21212182682938874
typography_spectrum: 0.6506013488397002
title: 96zero
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54281129-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.17782817455008626
  lightness: 0.3804633009713143
  saturation: 0.7904476055409759
  rhythmicContrast: 0.6619760245084763
purpose: []
