title: 96zero
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.718638
  brandStrength: 0.2831541
  lightness: 0.8154122
  brandColors:
    - '#4265A2'
    - '#E8D7BE'
    - '#023966'
    - '#3A411F'
    - '#88FFFF'
  rhythmicContrast: 0.4910394
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-54281129-1
  facebook: null
favicon: null
name: 96zero.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6506013488397002
layout_spectrum: 0.6487455
